In [ ]:
print("Hello world of python")

In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])

arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [8]:

arr1=np.array([[1,2,3],[4,5,6]])

arr1


array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(arr1.shape)

(2, 3)


In [11]:
arr2=np.arange(24).reshape(6,4)   # 2d array

print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [12]:
a=np.arange(24).reshape(2,3,4)  # 3d array

print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [13]:
a.max()

23

In [14]:
a.min()

0

In [15]:
a.sum()

276

In [18]:
#introduction to the statistical concepts

array([[4, 5, 6, 7]])

In [19]:
test_scores=np.array([39.5,54.5,84.1,41.2,27.9,58.9])

In [20]:
print("the mean of the test_scores")   # the mean of the test scores  x=x/n =sum of observations/no of observations

np.mean(test_scores)

the mean of the test_scores


51.01666666666667

In [21]:
print("the median of the test_scores")

np.median(test_scores)

the median of the test_scores


47.85