In [2]:
print("Hello world of python  daay 20!!!")

Hello world of python  daay 20!!!


In [3]:
import numpy as np

In [6]:
array_ones = np.ones((3,4))   # to print the array of ones

array_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
aray_ones_int=np.ones((3,4),dtype=np.int16)  # we are type casting the output from float to int

print(array_ones_int)

#The normal conversion with int as int16 or int32

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [14]:
array_2=np.full((3,4),7)  # we can go with print the required values

array_2



array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [13]:
print(array_2.shape)   # to know the shape of the array

(3, 4)


In [ ]:
#to print the array_empty  becasuse we don't know ehat kind of elements that have to come and later we have to fill it

In [16]:
array_empty =np.empty((2,3))  

array_empty

array([[1.48539705e-313, 1.48539705e-313, 1.48539705e-313],
       [1.48539705e-313, 1.48539705e-313, 1.48539705e-313]])

In [17]:
print(array_empty.shape)

(2, 3)


In [19]:
array_eye=np.eye(3)   # identity of matrix

array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:

# to print the range of values
# np.arrage(startvalue,endvalue,stepcount)

array_evens=np.arange(2,21,2)

array_evens


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])