In [1]:
print("Hello world of python !!!")

Hello world of python !!!


In [3]:
# basic opeartions in numpy

import numpy as np

In [4]:
a=np.array([10,10,10])

b=np.array([5,5,5])

In [5]:
a+b

array([15, 15, 15])

In [6]:
a-b

array([5, 5, 5])

In [7]:
a%2

array([0, 0, 0], dtype=int32)

In [12]:
a/2   # the default datatype is taken gives the values as decimal

array([5., 5., 5.])

In [9]:
a*b

array([50, 50, 50])

In [13]:
type(a)

numpy.ndarray

In [ ]:
#comparision opearators

In [14]:
a<21

array([ True,  True,  True])

In [16]:
b>=6

array([False, False, False])

In [17]:
a**2  # to print the square of the array


array([100, 100, 100], dtype=int32)

In [18]:
b**3  # to print the cube of the array

array([125, 125, 125], dtype=int32)

In [ ]:
req: how to modify the existing array
-------====================================

In [45]:
 a=np.array([10,10,10])
b=np.array([5,5,5])    

In [46]:
a

array([10, 10, 10])

In [47]:
a+=3

In [34]:
a

array([13, 13, 13])

In [48]:
b +=a

In [49]:
b

array([18, 18, 18])

In [ ]:
unary opeator:
=====    =========

In [55]:
ages=np.array([12,15,25,27])

ages

array([12, 15, 25, 27])

In [56]:
ages.sum()

79

In [57]:
ages.max()

27

In [58]:
ages.min()

12

In [60]:
print(ages.shape)

(4,)


In [62]:
numbers =np.arange(12).reshape(3,4)

In [63]:
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
a=np.array([(1,4,5),(7,8,11),(9,4,15)])

In [66]:
a

array([[ 1,  4,  5],
       [ 7,  8, 11],
       [ 9,  4, 15]])

In [67]:
a.shape

(3, 3)

In [76]:
a[0:,1]   

array([4, 8, 4])