In [1]:
print("Hello world of learning python !!!!")

Hello world of learning python !!!!


In [43]:
import numpy as np

In [12]:
a=np.array([[12,15,21] ,[15,1,24]])

In [13]:
print(a)

[[12 15 21]
 [15  1 24]]


In [14]:
a.shape


(2, 3)

In [41]:
 a[0:,2:3]

array([[21],
       [24]])

In [ ]:
# understanding the file formats

In [ ]:
data is new kind fuel
.csv -->comma sepeared value
.json---> java script object notation
.xlsx---->similar to xl sheet

In [45]:
salaries=np.genfromtxt('salary.csv',delimiter=',')

In [46]:
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [50]:
salaries.shape

(1147,)

In [ ]:
#req:I want to find out the mean of the salaries.

In [53]:
print("Mean of the salaries is given below:")
print(np.mean(salaries))

Mean of the salaries is given below:
55894.53879686138


In [55]:
print("The median of the salarie :\n")
print(np.median(salaries))

The median of the salarie :

48000.0


In [66]:
print("the varience of the salaries:\n")
print(np.var(salaries) )


the varience of the salaries:

3043770333.8474483


In [68]:
print(round(3043770333.8474483,3))  #round of  the values  round(x,no of digit after decimal)

3043770333.847


In [70]:
print("the standard deviation is:")
print(np.std(salaries))

the standard deviation is:
55170.37550939316
